use constants::supported_games::SupportedGames;
use std::fs;

fn main() {
    let md_path = "GAMES.md";
    let marker = "<!-- MARKER: Please update crates/constants/src/supported_games.json and run `cargo run --bin update-games` to update this file. Do not edit this file directly. -->";

    let mut games = SupportedGames::load_from_embedded();
    games.sort();

    let md_content = fs::read_to_string(md_path).expect("Failed to read GAMES.md");

    let marker_pos = md_content
        .find(marker)
        .expect("Marker not found in GAMES.md");
    let before_marker = &md_content[..marker_pos + marker.len()];

    let links: Vec<String> = games
        .games
        .iter()
        .map(|g| format!("- [{}]({})", g.game, g.url))
        .collect();

    let games_list = links.join("\n");

    let new_content = format!("{}\n\n{}\n", before_marker, games_list);

    fs::write(md_path, new_content).expect("Failed to write GAMES.md");

    println!("Updated GAMES.md with {} games", games.games.len());
}
