use serde::Deserialize;
use std::fs;

#[derive(Deserialize)]
struct Game {
    game: String,
    url: String,
}

fn main() {
    let json_path = "crates/constants/src/supported_games.json";
    let md_path = "GAMES.md";
    let marker = "<!-- MARKER: Please update crates/constants/src/supported_games.json and run `cargo run --bin update-games` to update this file. Do not edit this file directly. -->";

    let json_content = fs::read_to_string(json_path)
        .expect("Failed to read supported_games.json");
    let games: Vec<Game> = serde_json::from_str(&json_content)
        .expect("Failed to parse JSON");

    let md_content = fs::read_to_string(md_path)
        .expect("Failed to read GAMES.md");

    let marker_pos = md_content.find(marker)
        .expect("Marker not found in GAMES.md");
    let before_marker = &md_content[..marker_pos + marker.len()];

    let mut links: Vec<String> = games
        .iter()
        .map(|g| format!("- [{}]({})", g.game, g.url))
        .collect();
    links.sort_by(|a, b| a.to_lowercase().cmp(&b.to_lowercase()));

    let games_list = links.join("\n");

    let new_content = format!("{}\n\n{}\n", before_marker, games_list);

    fs::write(md_path, new_content)
        .expect("Failed to write GAMES.md");

    println!("Updated GAMES.md with {} games", games.len());
}
